export const profile = {
  email: 'fBayowa5@gmail.com',
  phone: '+2349039576654',
  phoneDisplay: '0903 957 6654',
  linkedin: 'https://www.linkedin.com/in/favour-bayowa-790564256',
  gse: 'https://gseacademy.nestuge.com',
  lede: 'I turn ideas, expertise, and products into content that earns attention, builds trust, and moves people to act.',
  close:
    'If you are building a brand, a product, a community, or a campaign, and you need someone who can think, write, and follow it through, I would be glad to contribute.',
}

export const roles = [
  {
    title: 'Content Strategist',
    line: 'I start with the audience and the action, then decide what to make.',
  },
  {
    title: 'Copywriter',
    line: 'Hooks, scripts, captions, and offers written to be acted on.',
  },
  {
    title: 'Audience Growth',
    line: 'Content that becomes a following, a community, and a room.',
  },
  {
    title: 'Conversion',
    line: 'Registrations, attendance, and products that actually sell.',
  },
]

export const marquee = [
  'GSE Academy',
  'JobsMusic',
  'RCF LASU',
  'The GrindSmart Effect',
  'Campus to Career',
  'Mastering AI Prompting',
  'Dreams to Reality',
  'Strategy',
  'Copy',
  'Community',
  'Conversion',
]

export const prints = [
  {
    id: 'book',
    src: '/images/book-grindsmart.jpg',
    alt: 'Cover of The GrindSmart Effect by Bayowa Favour',
    caption: 'the shelf',
    note: '300+ copies of The GrindSmart Effect sold in a month. Four books, one campus-to-career thread.',
    x: '0%',
    y: '0%',
    w: '32%',
    r: -8,
    z: 2,
    ratio: '3 / 4',
    position: 'center',
  },
  {
    id: 'campus',
    src: '/images/poster-campus.jpg',
    alt: 'Poster for Maximize Your Campus Years, with Bayowa Favour centered',
    caption: 'campus years',
    note: 'Maximize Your Campus Years. Educational campaigns that brought in 500+ registrations each.',
    x: '58%',
    y: '0%',
    w: '40%',
    r: 6,
    z: 3,
    ratio: '4 / 5',
    position: 'center 18%',
  },
  {
    id: 'summit',
    src: '/images/summit.jpg',
    alt: 'A packed lecture hall at the GSE Summit',
    caption: 'the room',
    note: 'GSE Summit. 1,000+ people registered. 700 came and sat down.',
    x: '16%',
    y: '24%',
    w: '50%',
    r: -2.5,
    z: 4,
    ratio: '5 / 4',
    position: 'center 42%',
  },
  {
    id: 'ladder',
    src: '/images/poster-20s.jpg',
    alt: 'Poster for Maximizing Your 20s: The Career Ladder, hosted by Bayowa Favour',
    caption: 'the ladder',
    note: 'Maximizing Your 20s. A three-day series built around the questions students were already asking.',
    x: '0%',
    y: '52%',
    w: '36%',
    r: -6,
    z: 3,
    ratio: '4 / 5',
    position: 'center 12%',
  },
  {
    id: 'analytics',
    src: '/images/analytics.jpg',
    alt: 'LinkedIn analytics showing 18,282 impressions in a week',
    caption: 'the receipt',
    note: '18,282 impressions in seven days, up 1,567% on the week before. 7,646 members reached.',
    x: '62%',
    y: '50%',
    w: '34%',
    r: 5,
    z: 2,
    ratio: '4 / 5',
    position: 'center 38%',
  },
]

export const results = [
  {
    start: 100,
    end: 6000,
    suffix: '+',
    label: 'LinkedIn followers in eight months',
    icon: 'linkedin',
    flagship: true,
    note: 'the biggest jump',
    tilt: -1.3,
    shift: 0,
    align: 'start',
    size: 'lg',
  },
  {
    start: 0,
    end: 1000,
    suffix: '+',
    label: 'Instagram followers in eight months',
    icon: 'instagram',
    tilt: 1.6,
    shift: '1.8rem',
    align: 'end',
    size: 'md',
  },
  {
    start: 500,
    end: 1200,
    suffix: '+',
    label: 'Artist YouTube subscribers',
    icon: 'youtube',
    tilt: -0.7,
    shift: '-0.5rem',
    align: 'start',
    size: 'sm',
  },
  {
    start: 50,
    end: 2500,
    suffix: '+',
    label: 'Spotify playlist listeners in two months',
    icon: 'spotify',
    tilt: 1.1,
    shift: '2.2rem',
    align: 'end',
    size: 'md',
  },
  {
    start: null,
    end: 600,
    suffix: '+',
    label: 'Content assets written and published',
    icon: 'pencil',
    tilt: -1.9,
    shift: '0.3rem',
    align: 'start',
    size: 'sm',
  },
  {
    start: 500,
    end: 1250,
    suffix: '',
    label: 'RCF event attendance in four months',
    icon: 'people',
    tilt: 0.8,
    shift: '-1.1rem',
    align: 'end',
    size: 'md',
  },
  {
    start: null,
    end: 1000,
    suffix: '+',
    label: 'Summit registrations, 700 people in the room',
    icon: 'mic',
    tilt: -0.4,
    shift: '1.9rem',
    align: 'start',
    size: 'lg',
  },
  {
    start: null,
    end: 300,
    suffix: '+',
    label: 'Book copies sold in a single month',
    icon: 'book',
    tilt: 1.4,
    shift: '-0.4rem',
    align: 'end',
    size: 'sm',
  },
]

export const steps = [
  {
    word: 'Stop',
    body: 'Earn the pause with a hook that belongs to this audience, not a generic opener.',
  },
  {
    word: 'Stay',
    body: 'Give them a reason to keep watching. Curiosity, relevance, and a promise you can keep.',
  },
  {
    word: 'Learn',
    body: 'Deliver something useful enough to remember. Practical, specific, and short enough to use.',
  },
  {
    word: 'Trust',
    body: 'Be clear, show evidence, and stay consistent. Expertise should feel calm, not loud.',
  },
  {
    word: 'Act',
    body: 'Ask for the next step while it still makes sense. A registration, a seat, a copy, a reply.',
  },
]

export const services = [
  {
    title: 'Content strategy',
    body: 'Positioning, pillars, and a plan tied to a business goal. Not a calendar kept alive for its own sake.',
  },
  {
    title: 'Copywriting',
    body: 'Social copy, scripts, product lines, email, and the line that asks someone to move.',
  },
  {
    title: 'Audience and campaigns',
    body: 'Growth, community, launches, and events. Attention carried through to a list, a room, or a sale.',
  },
  {
    title: 'Reading the numbers',
    body: 'What people watch, share, and ignore. Then the next piece changes because of it.',
  },
]

export const shelf = [
  {
    year: '2025',
    title: 'The audience',
    line: 'LinkedIn from 100 to 6,000+. Instagram from zero to 1,000+. Eight months, in public.',
    src: '/images/linkedin.jpg',
    alt: 'Favour Bayowa’s LinkedIn profile showing 6,045 followers',
    position: 'center 22%',
  },
  {
    year: '2025',
    title: 'A week of reach',
    line: '18,282 impressions. Most of them from people who did not already follow.',
    src: '/images/analytics.jpg',
    alt: 'Analytics chart climbing to 18,282 impressions',
    position: 'center 36%',
  },
  {
    year: '2025',
    title: 'GSE Summit',
    line: 'From a career conversation online to 700 people in a hall.',
    src: '/images/summit.jpg',
    alt: 'A packed lecture hall at the GSE Summit',
    position: 'center 42%',
  },
  {
    year: '2025',
    title: 'Campus Years',
    line: 'A webinar on becoming a complete student. 500+ registrations a campaign.',
    src: '/images/poster-campus.jpg',
    alt: 'Poster for Maximize Your Campus Years, with Bayowa Favour centered',
    position: 'center 18%',
  },
  {
    year: '2026',
    title: 'The Career Ladder',
    line: 'Three evenings on what happens after the degree, and how to get ready before it ends.',
    src: '/images/lasu-conscience.jpg',
    alt: 'LASU Conscience media event poster listing Bayowa Favour as a presidential panelist',
    position: 'center 38%',
  },
  {
    year: '2025',
    title: 'The GrindSmart Effect',
    line: 'Product, message, and a month that sold 300+ copies.',
    src: '/images/grindsmart-why.jpg',
    alt: 'Why Grind Smart Academy value-proposition graphic: strategy over hustle, skills that generate income',
    position: 'center',
  },
  {
    year: '2025',
    title: 'The shelf',
    line: 'The GrindSmart Effect, Campus to Career, Mastering AI Prompting, Dreams to Reality.',
    src: '/images/shop.jpg',
    alt: 'GSE shop page with Favour’s books',
    position: 'center 48%',
  },
  {
    year: '2025',
    title: 'The live room',
    line: 'Webinars that moved people from watching a post to showing up in the community.',
    src: '/images/webinar.jpg',
    alt: 'Bayowa Favour on stage in a fireside chat at a GSE live session',
    position: 'center 45%',
  },
  {
    year: '2025',
    title: 'JobsMusic',
    line: 'Release campaigns for a gospel project. YouTube 500 → 1,200+. A playlist from 50 to 2,500+ in two months.',
    src: '/images/jobsmusic.jpg',
    alt: 'Jobsmusic artist profile on Spotify with 4,702 monthly listeners',
    position: 'center 15%',
  },
  {
    year: '2024',
    title: 'RCF LASU',
    line: 'President. Communication and mobilisation that grew event attendance from 500 to 1,250 in four months.',
    src: '/images/rcf-lasu.jpg',
    alt: 'A crusade night at RCF LASU titled Taming Excesses, with the crowd raising their hands in worship',
    position: '65% 20%',
  },
]
